# Arrays con Numpy Parte II

## Números randómicos (aleatorios)

In [1]:
import numpy as np

## Funcion rand()

In [2]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [3]:
indicadores = np.random.rand(5)

In [4]:
indicadores

array([0.21629463, 0.35149975, 0.79545008, 0.82564294, 0.9264386 ])

In [5]:
indicadores.shape

(5,)

In [6]:
indicadores2 = np.random.rand(7, 5)

In [7]:
indicadores2

array([[0.039733  , 0.32973253, 0.30092916, 0.46912271, 0.24920002],
       [0.53348538, 0.40153434, 0.50296392, 0.96415376, 0.13408768],
       [0.30589207, 0.91620001, 0.74771806, 0.95853582, 0.9696956 ],
       [0.04071291, 0.75150687, 0.15167891, 0.9329745 , 0.67373854],
       [0.07003248, 0.03222195, 0.79266376, 0.49051285, 0.30459308],
       [0.87235332, 0.54407856, 0.37116935, 0.8322878 , 0.13819337],
       [0.66459642, 0.48882529, 0.28770367, 0.04054945, 0.91096373]])

## Funciones de ndarrays

In [8]:
indicadores2.min()

0.03222194561612546

In [9]:
indicadores2.max()

0.969695599738259

In [10]:
indicadores2.mean()

0.4918383107100898

In [11]:
indicadores2.sum()

17.214340874853143

In [12]:
indicadores2.sort()

In [13]:
indicadores2

array([[0.039733  , 0.24920002, 0.30092916, 0.32973253, 0.46912271],
       [0.13408768, 0.40153434, 0.50296392, 0.53348538, 0.96415376],
       [0.30589207, 0.74771806, 0.91620001, 0.95853582, 0.9696956 ],
       [0.04071291, 0.15167891, 0.67373854, 0.75150687, 0.9329745 ],
       [0.03222195, 0.07003248, 0.30459308, 0.49051285, 0.79266376],
       [0.13819337, 0.37116935, 0.54407856, 0.8322878 , 0.87235332],
       [0.04054945, 0.28770367, 0.48882529, 0.66459642, 0.91096373]])

In [14]:
indicadores2.var()

0.0970529000971461

In [15]:
indicadores2.std()

0.31153314446001745

## Funcion randint()

In [16]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [17]:
np.random.randint(1, 100, 15)

array([45, 78,  4, 44, 75,  7, 69, 25, 34, 44, 31, 87, 64, 92, 13])

In [18]:
np.random.randint(1, 100, size=(5, 4))

array([[22, 32, 98, 41],
       [74, 97, 46, 70],
       [36, 12, 12, 42],
       [67, 22, 82, 13],
       [ 8, 71, 79, 81]])

In [19]:
temperaturas = np.random.randint(20, 25, size=(30, 7))

In [20]:
temperaturas

array([[22, 23, 22, 24, 21, 24, 23],
       [22, 24, 23, 21, 24, 20, 21],
       [20, 22, 24, 21, 21, 20, 23],
       [21, 20, 21, 20, 23, 24, 22],
       [21, 24, 24, 21, 23, 21, 20],
       [23, 24, 24, 23, 20, 23, 23],
       [21, 24, 22, 20, 22, 20, 21],
       [20, 22, 23, 21, 24, 24, 22],
       [21, 22, 21, 23, 20, 21, 21],
       [22, 23, 23, 23, 21, 24, 20],
       [23, 22, 24, 23, 24, 20, 23],
       [23, 22, 22, 23, 21, 22, 20],
       [20, 24, 24, 23, 22, 21, 22],
       [22, 21, 23, 23, 24, 21, 21],
       [21, 21, 22, 20, 22, 23, 20],
       [20, 22, 21, 20, 20, 20, 22],
       [20, 23, 20, 24, 21, 22, 21],
       [24, 20, 20, 22, 22, 21, 21],
       [22, 22, 21, 20, 21, 22, 22],
       [21, 21, 20, 22, 21, 24, 22],
       [22, 21, 23, 22, 22, 21, 23],
       [20, 23, 23, 21, 23, 21, 20],
       [21, 24, 22, 21, 20, 24, 22],
       [23, 23, 21, 20, 21, 20, 21],
       [20, 22, 24, 22, 23, 24, 23],
       [24, 22, 20, 24, 22, 23, 21],
       [20, 23, 22, 21, 20, 23, 23],
 

In [21]:
delta = np.random.rand(30, 7)

In [22]:
delta

array([[0.92922276, 0.91004793, 0.74095593, 0.89285706, 0.88501367,
        0.18386337, 0.43155975],
       [0.0760954 , 0.06919399, 0.31168521, 0.20832037, 0.61125278,
        0.50229368, 0.04513961],
       [0.28569905, 0.87105416, 0.74020763, 0.46393167, 0.71915443,
        0.55272583, 0.31267504],
       [0.22329481, 0.28947072, 0.14754362, 0.70425876, 0.08579921,
        0.75953836, 0.73000992],
       [0.63210638, 0.3314203 , 0.90880581, 0.8390612 , 0.94394674,
        0.1694876 , 0.21604408],
       [0.92515298, 0.00429157, 0.22933409, 0.05963187, 0.74563007,
        0.32915622, 0.21510484],
       [0.56290542, 0.78887856, 0.93013946, 0.77450426, 0.04582245,
        0.71232117, 0.50346614],
       [0.5322    , 0.41967155, 0.85441485, 0.13966267, 0.10595865,
        0.76734848, 0.43494467],
       [0.55268415, 0.32338581, 0.25964597, 0.22878214, 0.27688454,
        0.40037786, 0.54497354],
       [0.56426378, 0.06589757, 0.11898865, 0.31634323, 0.64354151,
        0.3217018 , 0.9

In [23]:
temperaturas.shape

(30, 7)

In [24]:
delta.shape

(30, 7)

In [25]:
temps = temperaturas + delta

In [26]:
temps

array([[22.92922276, 23.91004793, 22.74095593, 24.89285706, 21.88501367,
        24.18386337, 23.43155975],
       [22.0760954 , 24.06919399, 23.31168521, 21.20832037, 24.61125278,
        20.50229368, 21.04513961],
       [20.28569905, 22.87105416, 24.74020763, 21.46393167, 21.71915443,
        20.55272583, 23.31267504],
       [21.22329481, 20.28947072, 21.14754362, 20.70425876, 23.08579921,
        24.75953836, 22.73000992],
       [21.63210638, 24.3314203 , 24.90880581, 21.8390612 , 23.94394674,
        21.1694876 , 20.21604408],
       [23.92515298, 24.00429157, 24.22933409, 23.05963187, 20.74563007,
        23.32915622, 23.21510484],
       [21.56290542, 24.78887856, 22.93013946, 20.77450426, 22.04582245,
        20.71232117, 21.50346614],
       [20.5322    , 22.41967155, 23.85441485, 21.13966267, 24.10595865,
        24.76734848, 22.43494467],
       [21.55268415, 22.32338581, 21.25964597, 23.22878214, 20.27688454,
        21.40037786, 21.54497354],
       [22.56426378, 23.0658

## Axis en NumPy

En numpy las filas se refieren al axis=1, y las columnas al axis=0

![Image](images/array_axis.png)

In [28]:
notas_alumnos = np.random.randint(1, 101, size=(15, 3))

In [29]:
notas_alumnos

array([[49, 67, 55],
       [98,  9, 33],
       [83, 55, 78],
       [68, 20, 72],
       [82, 16, 25],
       [48, 39, 24],
       [67, 78, 40],
       [93, 70, 16],
       [17, 66, 41],
       [20, 51, 56],
       [39, 44, 30],
       [64, 25, 76],
       [ 4, 35, 29],
       [71, 43, 83],
       [94, 24, 76]])

In [30]:
notas_alumnos.sum(axis=0)

array([897, 642, 734])

In [31]:
notas_alumnos.sum(axis=1)

array([171, 140, 216, 160, 123, 111, 185, 179, 124, 127, 113, 165,  68,
       197, 194])

In [32]:
49 + 67 + 55

171

In [33]:
# calcular

In [34]:
notas_alumnos.mean(axis=0)

array([59.8       , 42.8       , 48.93333333])

In [35]:
notas_alumnos.mean(axis=1)

array([57.        , 46.66666667, 72.        , 53.33333333, 41.        ,
       37.        , 61.66666667, 59.66666667, 41.33333333, 42.33333333,
       37.66666667, 55.        , 22.66666667, 65.66666667, 64.66666667])

In [37]:
# operaciones sobre filas específicas

In [38]:
notas_alumnos

array([[49, 67, 55],
       [98,  9, 33],
       [83, 55, 78],
       [68, 20, 72],
       [82, 16, 25],
       [48, 39, 24],
       [67, 78, 40],
       [93, 70, 16],
       [17, 66, 41],
       [20, 51, 56],
       [39, 44, 30],
       [64, 25, 76],
       [ 4, 35, 29],
       [71, 43, 83],
       [94, 24, 76]])

In [39]:
notas_alumnos[1]

array([98,  9, 33])

In [40]:
notas_alumnos[1].mean()

46.666666666666664

In [41]:
(98 + 9 + 33) / 3

46.666666666666664