# Arrays con Numpy Parte II

## Números randómicos (aleatorios)

In [1]:
import numpy as np

## Funcion rand()

In [3]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [4]:
indicadores = np.random.rand(5)

In [5]:
indicadores

array([0.08996151, 0.61349207, 0.31605669, 0.54051235, 0.95956628])

In [6]:
indicadores.shape

(5,)

In [9]:
indicadores2 = np.random.rand(7, 5)

In [10]:
indicadores2

array([[0.98866992, 0.33408582, 0.39411921, 0.58203199, 0.13067702],
       [0.83881424, 0.38645502, 0.70753973, 0.65484341, 0.39026396],
       [0.64259014, 0.61330157, 0.54178822, 0.07521541, 0.54668758],
       [0.196157  , 0.8265249 , 0.15856422, 0.80981388, 0.97526163],
       [0.3335602 , 0.8963089 , 0.47529287, 0.02545492, 0.02044262],
       [0.84895736, 0.69588948, 0.47889207, 0.60293819, 0.07109706],
       [0.30244693, 0.24568932, 0.21382738, 0.58223992, 0.26067621]])

## Funciones de ndarrays

In [12]:
indicadores2.min()

0.02044262065527902

In [13]:
indicadores2.max()

0.9886699154029451

In [14]:
indicadores2.mean()

0.48134623726362935

In [15]:
indicadores2.sum()

16.847118304227028

In [16]:
indicadores2.sort()

In [17]:
indicadores2

array([[0.13067702, 0.33408582, 0.39411921, 0.58203199, 0.98866992],
       [0.38645502, 0.39026396, 0.65484341, 0.70753973, 0.83881424],
       [0.07521541, 0.54178822, 0.54668758, 0.61330157, 0.64259014],
       [0.15856422, 0.196157  , 0.80981388, 0.8265249 , 0.97526163],
       [0.02044262, 0.02545492, 0.3335602 , 0.47529287, 0.8963089 ],
       [0.07109706, 0.47889207, 0.60293819, 0.69588948, 0.84895736],
       [0.21382738, 0.24568932, 0.26067621, 0.30244693, 0.58223992]])

In [18]:
indicadores2.var()

0.07758567306281847

In [19]:
indicadores2.std()

0.27854204900305174

## Funcion randint()

In [20]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [21]:
np.random.randint(1, 100, 15)

array([33, 38, 24, 16, 71, 83, 30, 97, 83, 71, 25, 82, 94,  1, 84])

In [22]:
np.random.randint(1, 100, size=(5, 4))

array([[67,  3, 66, 48],
       [51, 23, 37, 96],
       [95, 19, 66, 62],
       [49, 94, 65, 21],
       [82, 24, 14, 22]])

In [23]:
temperaturas = np.random.randint(20, 25, size=(30, 7))

In [24]:
temperaturas

array([[20, 23, 21, 21, 23, 22, 24],
       [23, 21, 20, 21, 20, 21, 20],
       [21, 24, 22, 20, 23, 21, 24],
       [20, 22, 23, 22, 21, 24, 24],
       [24, 24, 21, 22, 21, 21, 22],
       [24, 20, 21, 20, 23, 24, 23],
       [20, 24, 24, 20, 21, 23, 24],
       [23, 20, 23, 22, 20, 20, 21],
       [24, 22, 23, 21, 22, 23, 20],
       [21, 23, 24, 24, 23, 20, 22],
       [21, 21, 22, 22, 20, 21, 23],
       [21, 20, 24, 21, 20, 23, 20],
       [22, 22, 23, 23, 22, 20, 21],
       [23, 20, 21, 20, 20, 21, 24],
       [23, 23, 22, 22, 24, 20, 22],
       [22, 24, 22, 20, 20, 20, 21],
       [20, 23, 24, 23, 24, 20, 23],
       [24, 20, 24, 24, 20, 23, 24],
       [24, 20, 20, 22, 20, 22, 22],
       [24, 23, 22, 21, 23, 21, 20],
       [23, 24, 22, 20, 24, 20, 20],
       [20, 20, 22, 24, 21, 22, 22],
       [21, 21, 24, 22, 23, 22, 24],
       [23, 24, 23, 22, 21, 24, 23],
       [23, 22, 23, 20, 22, 22, 20],
       [22, 23, 22, 23, 22, 24, 20],
       [23, 20, 20, 20, 20, 24, 21],
 

In [25]:
delta = np.random.rand(30, 7)

In [26]:
delta

array([[0.40668702, 0.01732886, 0.50469123, 0.207384  , 0.35244755,
        0.84409777, 0.51757936],
       [0.88302244, 0.13958916, 0.20231934, 0.66104862, 0.36543658,
        0.31400093, 0.98851785],
       [0.70315138, 0.51079151, 0.02712875, 0.01685903, 0.51483028,
        0.05565623, 0.19187148],
       [0.31472958, 0.05233688, 0.46777781, 0.52925598, 0.14584544,
        0.76634723, 0.24265241],
       [0.93731672, 0.13678812, 0.77746595, 0.86512057, 0.33131928,
        0.36552373, 0.67632552],
       [0.33397939, 0.63544861, 0.71032491, 0.44342916, 0.77527015,
        0.68952307, 0.76371448],
       [0.05585435, 0.26196925, 0.95672185, 0.01682646, 0.15341511,
        0.23140648, 0.32357077],
       [0.41972675, 0.93756803, 0.8556299 , 0.84173138, 0.66619476,
        0.94060288, 0.95479786],
       [0.17965445, 0.57923555, 0.30770629, 0.57451482, 0.08395345,
        0.17087822, 0.0203999 ],
       [0.01624197, 0.43116121, 0.32765788, 0.99689326, 0.41839228,
        0.03977916, 0.9

In [27]:
temperaturas.shape

(30, 7)

In [28]:
delta.shape

(30, 7)

In [29]:
temps = temperaturas + delta

In [30]:
temps

array([[20.40668702, 23.01732886, 21.50469123, 21.207384  , 23.35244755,
        22.84409777, 24.51757936],
       [23.88302244, 21.13958916, 20.20231934, 21.66104862, 20.36543658,
        21.31400093, 20.98851785],
       [21.70315138, 24.51079151, 22.02712875, 20.01685903, 23.51483028,
        21.05565623, 24.19187148],
       [20.31472958, 22.05233688, 23.46777781, 22.52925598, 21.14584544,
        24.76634723, 24.24265241],
       [24.93731672, 24.13678812, 21.77746595, 22.86512057, 21.33131928,
        21.36552373, 22.67632552],
       [24.33397939, 20.63544861, 21.71032491, 20.44342916, 23.77527015,
        24.68952307, 23.76371448],
       [20.05585435, 24.26196925, 24.95672185, 20.01682646, 21.15341511,
        23.23140648, 24.32357077],
       [23.41972675, 20.93756803, 23.8556299 , 22.84173138, 20.66619476,
        20.94060288, 21.95479786],
       [24.17965445, 22.57923555, 23.30770629, 21.57451482, 22.08395345,
        23.17087822, 20.0203999 ],
       [21.01624197, 23.4311